### ISSUE TITLE
stepu command failed 

### ISSUE THREAD

**Issue by jiayuehua** [jefftrull/gdb_python_api#5] opened 2021-04-29 15:35 UTC
I failed to make  stepu command work. I use g++10.2 compile the code . And when run stepu, an error appear: parsing translation unit. I don't know how to make stepu work. 
![Gdb](https://user-images.githubusercontent.com/3423893/116576328-0adb1e00-a942-11eb-8b6f-cb72e26a98e8.png)
![gdbA](https://user-images.githubusercontent.com/3423893/116576333-0c0c4b00-a942-11eb-802c-e2e8889ffddb.png)

the tests in llvm-project/clang/bindings/python all have success passed.
![image](https://user-images.githubusercontent.com/3423893/116577522-1f6be600-a943-11eb-9743-2511c9ca2e32.png)

**Comment by jefftrull** [comment] 2021-05-01 05:12
Do you see any error regarding `stddef.h` ? If so this may be the same as #3

**Comment by jiayuehua** [comment] 2021-05-01 19:03
No, I haven't see stddef.h in error message. All I see is in the screenshot.

**Comment by jefftrull** [comment] 2021-05-02 04:34
Hm OK. I can't reproduce it - yet, anyway. Can you also show what you did in between the first and second screenshots?  And if you can, actually copy the text instead of taking a screenshot, thanks.

In the meantime I will try to fix the stddef.h issue in case it is impacting you in some other way.

**Comment by jiayuehua** [comment] 2021-05-02 06:44
Ok, I will post it today.

**Comment by jiayuehua** [comment] 2021-05-02 08:00
/mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-Clang-Debug$ tail  compile_commands.json 
  "directory": "/mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-Clang-Debug",
  "command": "/usr/bin/clang++ -DFMT_HEADER_ONLY=1 -I../../../game24 -isystem /home/rob/openSrc/vcpkg/installed/x64-linux/include -fno-limit-debug-info -g -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -std=gnu++2a -o game24/CMakeFiles/aoc170802.dir/aoc170802.cpp.o -c /mnt/c/Users/jiayu/source/repos/game24/game24/aoc170802.cpp",
  "file": "/mnt/c/Users/jiayu/source/repos/game24/game24/aoc170802.cpp"
},
{
  "directory": "/mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-Clang-Debug",
  "command": "/usr/bin/clang++ -DFMT_HEADER_ONLY=1 -I../../../game24 -isystem /home/rob/openSrc/vcpkg/installed/x64-linux/include -fno-limit-debug-info -g -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -std=gnu++2a -o game24/CMakeFiles/stl_with_lambda.dir/stl_with_lambda.cpp.o -c /mnt/c/Users/jiayu/source/repos/game24/game24/stl_with_lambda.cpp",
  "file": "/mnt/c/Users/jiayu/source/repos/game24/game24/stl_with_lambda.cpp"
}
]%                                                                                                                                    
/mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-Clang-Debug$ PYTHONPATH=/home/rob/openSrc/gdb_python_api:/home/rob/openSrc/llvm-project/clang/bindings/python/ LD_LIBRARY_PATH=/usr/lib/llvm-11/lib gdb
GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file game24/stl_with_lambda 
Reading symbols from game24/stl_with_lambda...
(gdb) py import gdb_uitl.stepping
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gdb_uitl'
Error while executing Python code.
(gdb) py import gdb_util.stepping
(gdb) b main
Breakpoint 1 at 0x402354: file ../../../game24/stl_with_lambda.cpp, line 25.
(gdb) r
Starting program: /mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-Clang-Debug/game24/stl_with_lambda 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main () at ../../../game24/stl_with_lambda.cpp:25
25          std::vector<Strings> data{
(gdb) stepu
Python Exception <class 'clang.cindex.TranslationUnitLoadError'> Error parsing translation unit.: 
Error occurred in Python: Error parsing translation unit.
(gdb)

**Comment by jefftrull** [comment] 2021-05-02 10:36
OK I have another idea. I see from your log that you are using clang++11, not gcc. When I do that I get a similar message but complaining about a missing `vector` header. Can you try removing `-stdlib=libc++` from your `compile_commands.json` file? It will appear in many places.

**Comment by jiayuehua** [comment] 2021-05-02 10:48
i will try right now.

**Comment by jefftrull** [comment] 2021-05-02 11:01
Also if possible can you give the output of `python import sys;print(sys.version)` from within gdb?

**Comment by jiayuehua** [comment] 2021-05-02 11:30
```
 5963  sudo apt install libc++-13-dev

 5967  sudo apt install libc++abi-13-dev
```
likely to use libc++ we need to do those operations. After do that, when compiling compiler can find <vector> header. I used to use clang++-13 but I just tried g++-11 have same issue. I will run print(sys.version) right now.

**Comment by jiayuehua** [comment] 2021-05-02 11:41
(gdb) python import sys;print(sys.version)
3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]

**Comment by jiayuehua** [comment] 2021-05-02 11:41
(gdb) python import sys;print(sys.version)
3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]

**Comment by jiayuehua** [comment] 2021-05-02 11:43
this is the output when  using  gcc-11 libstdc++ .
[gdb.txt](https://github.com/jefftrull/gdb_python_api/files/6411250/gdb.txt)

**Comment by jefftrull** [comment] 2021-05-02 15:47
You need to actually run it - you did `b main` but not `r` before the `stepu`. The error message tells you:

`gdb got an error trying to find our location. Maybe we are not currently running?`

**Comment by jiayuehua** [comment] 2021-05-02 16:03
still not work
just like before.

(gdb) cd build/WSL-GCC-Debug/
Working directory /mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-GCC-Debug.
(gdb) py import gdb_util.stepping
(gdb) b main
No symbol table is loaded.  Use the "file" command.
Make breakpoint pending on future shared library load? (y or [n]) n
(gdb) file game24/stl_with_lambda 
Reading symbols from game24/stl_with_lambda...
(gdb) b main
Breakpoint 1 at 0x255c: file ../../../game24/stl_with_lambda.cpp, line 20.
(gdb) r
Starting program: /mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-GCC-Debug/game24/stl_with_lambda 

Breakpoint 1, main () at ../../../game24/stl_with_lambda.cpp:20
20      int main() {
(gdb) stepu
Python Exception <class 'clang.cindex.TranslationUnitLoadError'> Error parsing translation unit.: 
Error occurred in Python: Error parsing translation unit.

**Comment by jiayuehua** [comment] 2021-05-02 16:04
still not work
just like before.

(gdb) cd build/WSL-GCC-Debug/
Working directory /mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-GCC-Debug.
(gdb) py import gdb_util.stepping
(gdb) b main
No symbol table is loaded.  Use the "file" command.
Make breakpoint pending on future shared library load? (y or [n]) n
(gdb) file game24/stl_with_lambda 
Reading symbols from game24/stl_with_lambda...
(gdb) b main
Breakpoint 1 at 0x255c: file ../../../game24/stl_with_lambda.cpp, line 20.
(gdb) r
Starting program: /mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-GCC-Debug/game24/stl_with_lambda 

Breakpoint 1, main () at ../../../game24/stl_with_lambda.cpp:20
20      int main() {
(gdb) stepu
Python Exception <class 'clang.cindex.TranslationUnitLoadError'> Error parsing translation unit.: 
Error occurred in Python: Error parsing translation unit.

**Comment by jefftrull** [comment] 2021-05-03 00:03
OK I've added some extra diagnostics - can you update and try again? It should fail, but with more information.

**Comment by jiayuehua** [comment] 2021-05-03 05:37
(gdb) stepu
Python Exception <class 'NameError'> name 'clang' is not defined: 
Error occurred in Python: name 'clang' is not defined

**Comment by jefftrull** [comment] 2021-05-03 16:39
I messed up the diagnostics :( Can you try again with the latest?

**Comment by jiayuehua** [comment] 2021-05-03 17:27
TranslationUnitLoadError while parsing ../../../game24/stl_with_lambda.cpp with args:
['--driver-mode=g++', '-DFMT_HEADER_ONLY=1', '-isystem', '/home/rob/openSrc/vcpkg/installed/x64-linux/include', '-g', '-Wall', '-Wextra', '-Wshadow', '-Wnon-virtual-dtor', '-Wold-style-cast', '-Wcast-align', '-Wunused', '-Woverloaded-virtual', '-Wpedantic', '-Wconversion', '-Wsign-conversion', '-Wnull-dereference', '-Wdouble-promotion', '-Wformat=2','-Wmisleading-indentation', '-Wduplicated-cond', '-Wduplicated-branches', '-Wlogical-op', '-Wuseless-cast', '../../../game24/stl_with_lambda.cpp']
Python Exception <class 'clang.cindex.TranslationUnitLoadError'>Errorparsing translation unit.: 
Error occurred in Python: Error parsing translation unit.
(gdb) pwd
Working directory /mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-GCC-Debug.
(gdb) shell ls ../../../game24/stl_with_lambda.cpp 
../../../game24/stl_with_lambda.cpp
(gdb) l 
15 
16      #include "detail.h"

**Comment by jefftrull** [comment] 2021-05-03 18:31
Well, I have tried many different things and I cannot reproduce your issue.

Can you create an MWE (minimum working example) for me and upload it to Github?

**Comment by jiayuehua** [comment] 2021-05-03 18:33
what is the example should contain?

**Comment by jiayuehua** [comment] 2021-05-03 18:36
Do you mean I upload my project that compile stl_with_lambda.cpp?

**Comment by jefftrull** [comment] 2021-05-03 18:41
If it's not a secret, that would be fine. If your code is proprietary, make a minimal (as small as possible) version that demonstrates the problem.

Is it this one: https://github.com/jiayuehua/game24 ? If so I could try it.

**Comment by jefftrull** [comment] 2021-05-03 18:43
I need to know the exact commands you used to build with gdb_python_api though.

**Comment by jiayuehua** [comment] 2021-05-03 18:43
I haven't upload stl_with_lambda.cpp , totally not secret. Wait a moment. Just lack that file.

**Comment by jiayuehua** [comment] 2021-05-03 19:05
Jeff I have uploaded , game24/stl_with_lambda.cpp

**Comment by jefftrull** [comment] 2021-05-03 19:23
OK. I think maybe I duplicated it? The problem is you did a release build - I think. Why this is a problem I'm not sure, but without a debug build you will not get very good results anyway.

Try again with `cmake -DCMAKE_BUILD_TYPE=Debug ..`

**Comment by jiayuehua** [comment] 2021-05-03 19:26
I did debug build. You can see my commands.json has -g flag.

**Comment by jefftrull** [comment] 2021-05-03 19:48
I see. Nevertheless I can reproduce your error _only_ when I use `CMAKE_BUILD_TYPE=RelWithDebInfo` and not when I use `CMAKE_BUILD_TYPE=Debug`. I'm not sure why yet. Both of those have the `-g` flag.

**Comment by jiayuehua** [comment] 2021-05-03 20:04
Hmm. CmakeSettings.json line 28 show that I also use debug not relwithdbg.

**Comment by jefftrull** [comment] 2021-05-03 21:26
Can you try this?

`set( CMAKE_CXX_FLAGS_DEBUG "-g -O0" )`

**Comment by jiayuehua** [comment] 2021-05-04 04:24
just tried , likely still the same as before.

(gdb) stepu
TranslationUnitLoadError while parsing ../../../game24/stl_with_lambda.cpp with args:
['--driver-mode=g++', '-DFMT_HEADER_ONLY=1', '-I../../../game24', '-isystem', '/home/rob/openSrc/vcpkg/installed/x64-linux/include', '-g', '-O0', '-Wall', '-Wextra', '-Wshadow', '-Wnon-virtual-dtor', '-Wold-style-cast', '-Wcast-align', '-Wunused', '-Woverloaded-virtual', '-Wpedantic', '-Wconversion', '-Wsign-conversion', '-Wnull-dereference', '-Wdouble-promotion', '-Wformat=2', '-Wmisleading-indentation', '-Wduplicated-cond', '-Wduplicated-branches', '-Wlogical-op', '-Wuseless-cast', '../../../game24/stl_with_lambda.cpp']
Python Exception <class 'clang.cindex.TranslationUnitLoadError'> Error parsing translation unit.: 
Error occurred in Python: Error parsing translation unit.
(gdb) l
15 
16      #include "detail.h"
17 
18      using namespace detail;
19 
20      int main() {
21          // (broken) attempt at lexicographic sort
22 
23          using Strings = std::vector<std::string>;
24

**Comment by jefftrull** [comment] 2021-05-06 20:09
I've made some improvements to the code that may help your situation. Can you try again?

**Comment by jiayuehua** [comment] 2021-05-07 12:25
(gdb) file game24/stl_with_lambda 
Reading symbols from game24/stl_with_lambda...
(gdb) b main
Breakpoint 1 at 0xd112: file ../../../game24/stl_with_lambda.cpp, line 20.
(gdb) r
Starting program: /mnt/c/Users/jiayu/source/repos/advent_of_code/adventOfCode/out/build/WSL-GCC-Debug/game24/stl_with_lambda 

Breakpoint 1, main () at ../../../game24/stl_with_lambda.cpp:20
20      int main() {
(gdb) py import gdb_util.stepping
(gdb) stepu
Python Exception <class 'RuntimeError'> cannot find the translation unit for file ../../../game24/stl_with_lambda.cpp: 
Error occurred in Python: cannot find the translation unit for file ../../../game24/stl_with_lambda.cpp

**Comment by jefftrull** [comment] 2021-05-07 19:54
This is a more helpful error, actually. It's failing early because it cannot locate `../../../game24/stl_with_lambda.cpp` in the compilation database.

Actually there is an interesting difference here. When you break in `main()` you get:
`Breakpoint 1 at 0x402354: file ../../../game24/stl_with_lambda.cpp, line 25.`

but I get:
`Breakpoint 1, main () at /tmp/game24/game24/stl_with_lambda.cpp:20`

Yours gives a _relative_ path, while mine uses an _absolute_ one.

Can you show me how you run cmake? I wonder if that can explain it.

**Comment by jefftrull** [comment] 2021-05-07 20:08
I changed the code to support relative paths - but do please show me how you run CMake. It's an interesting difference.

**Comment by jiayuehua** [comment] 2021-05-08 11:03
Jeff, I use visual studio cmake template and target wsl. This is the output when visual studio generate cache.

1> CMake generation started for configuration: 'WSL-GCC-Debug'.
1> Found cmake executable at cmake.
1> Found and using vcpkg toolchain file (/home/rob/openSrc/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> cmake -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="/mnt/c/Users/jiayu/source/repos/advent_of_code/adventOfCode/out/install/WSL-GCC-Debug" -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_TOOLCHAIN_FILE="/home/rob/openSrc/vcpkg/scripts/buildsystems/vcpkg.cmake" /mnt/c/Users/jiayu/source/repos/advent_of_code/adventOfCode/CMakeLists.txt;
1> [CMake] -- ccache found and enabled
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: /mnt/c/Users/jiayu/source/repos/advent_of_code/adventOfCode/out/build/WSL-GCC-Debug
1> [CMake] 
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted includes paths.
1> CMake generation finished.

**Comment by jiayuehua** [comment] 2021-05-08 11:32
After update the code:
(gdb) stepu
[":unknown warning option '-Wduplicated-cond'", ":unknown warning option '-Wduplicated-branches'", ":unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'?", ":unknown warning option '-Wuseless-cast'"]
Python Exception <class 'RuntimeError'> Failure during libclang parsing: 
Error occurred in Python: Failure during libclang parsing
(gdb) quit


And after I keep just -Wextra and -Wall warning options:
(gdb) stepu

Breakpoint -30, main () at ../../../game24/stl_with_lambda.cpp:28
28              {"Monoid", "Endofunctor", "Monad"}};
(gdb) l
23          using Strings = std::vector<std::string>;
24 
25          std::vector<Strings> data{
26              {"Frodo", "Sam", "Smeagol"},
27              {"Foo", "Bar", "Baz"},
28              {"Monoid", "Endofunctor", "Monad"}};
29 
30          // sample code targets the beginning of this call:
31          std::sort(data.begin(), data.end(),
32                    [](Strings const & a, Strings const & b) {
(gdb) stepu
Python Exception <class 'RuntimeError'> AST node on line 28 is not a child of a compound statement - cannot determine next statement: 
Error occurred in Python: AST node on line 28 is not a child of a compound statement - cannot determine next statement

Should `stepu` be able to let gdb pause at line 32?

**Comment by jefftrull** [comment] 2021-05-08 17:34
That makes sense, actually - there is no user code to step to on that line, and the line itself is in the middle of a braced initialization. What happens when you `stepu` from line 31 (the `std::sort` which is my main test case)?

Also I was curious about something I noticed earlier. It looks like you are using a custom LLVM build, but referring to the system's LLVM libraries: `PYTHONPATH` includes `/home/rob/openSrc/llvm-project/clang/bindings/python/` but `LD_LIBRARY_PATH` is `/usr/lib/llvm-11/lib`. Can you try using `LD_LIBRARY_PATH=/home/rob/openSrc/llvm-project/build/lib` (or wherever your custom build puts it) instead?

**Comment by jefftrull** [comment] 2021-05-08 19:24
Also what version of LLVM is your custom build? It needs to be 11.1 and not 11.0 (which has a bug).

**Comment by jiayuehua** [comment] 2021-05-10 20:30
- if first use stepu on line 28

(gdb) n
28              {"Monoid", "Endofunctor", "Monad"}};
(gdb) stepu
Python Exception <class 'RuntimeError'> AST node on line 28 is not a child of a compound statement - cannot determine next statement: 
Error occurred in Python: AST node on line 28 is not a child of a compound statement - cannot determine next statement

- if first use stepu on line 31
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /mnt/c/Users/jiayu/source/repos/game24/out/build/WSL-GCC-Debug/game24/stl_with_lambda 

Breakpoint 1, main () at ../../../game24/stl_with_lambda.cpp:20
20      int main() {
(gdb) n
28              {"Monoid", "Endofunctor", "Monad"}};
(gdb) n
31          std::sort(data.begin(), data.end(),
(gdb) stepu

Breakpoint -47, main () at ../../../game24/stl_with_lambda.cpp:41
41          do_something(f);


My system has llvm 11.1 installed ,  Beacause My system didn't install python binding and apt can't install it, so I pull llvm repo and  use llvmorg-11.1.0 branch `bindings/python`

**Comment by jefftrull** [comment] 2021-05-10 20:59
Great, this is good progress. We no longer see your original problem.

The `stepu` from line 31 works for me when using 11.1. I only see it fail to find the lambda under two situations:
1. If I use 11.0 instead of 11.1 (Ubuntu's llvm-11 package installs 11.0)
2. If I build with optimization turned on

Can you try pointing `LD_LIBRARY_PATH` to your llvm repo instead of the system?

**Comment by jiayuehua** [comment] 2021-05-10 21:02
Later I will build llvm. Now I only has source repo.

**Comment by jefftrull** [comment] 2021-05-10 21:20
Also, I don't know about WSL but the clang Python bindings are available from apt as `python3-clang-11` on Ubuntu. It's 11.0.

**Comment by jiayuehua** [comment] 2021-05-15 08:06
Hello, Jeff. Today I update Python bindings to python3-clang-13 and now stepu can work. stepu not work with python3-clang-11 on my machine.

/mnt/c/Users/jiayu/source/repos/advent_of_code/adventOfCode/out/build/WSL-GCC-Debug$ PYTHONPATH=/home/rob/openSrc/gdb_python_api LD_LIBRARY_PATH=/usr/lib/llvm-13/lib gdb                                                                                                   
GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) pwd
Working directory /mnt/c/Users/jiayu/source/repos/advent_of_code/adventOfCode/out/build/WSL-GCC-Debug.
(gdb) file game24/
CMakeFiles/          argot                cmake_install.cmake  game24               stl_with_lambda      
(gdb) file game24/
CMakeFiles/          argot                cmake_install.cmake  game24               stl_with_lambda      
(gdb) file game24/
CMakeFiles/          argot                cmake_install.cmake  game24               stl_with_lambda      
(gdb) file game24/stl_with_lambda 
Reading symbols from game24/stl_with_lambda...
(gdb) b main
Breakpoint 1 at 0x9a3d: file ../../../game24/stl_with_lambda.cpp, line 20.
(gdb) l
6       #else
7       #define INLINECTL
8       #endif
9 
10      #include <vector>
11      #include <algorithm>
12      #include <iostream>
13      #include <iterator>
14      #include <string>
15 
(gdb) r
Starting program: /mnt/c/Users/jiayu/source/repos/advent_of_code/adventOfCode/out/build/WSL-GCC-Debug/game24/stl_with_lambda 

Breakpoint 1, main () at ../../../game24/stl_with_lambda.cpp:20
20      int main() {
(gdb) n
28              {"Monoid", "Endofunctor", "Monad"}};
(gdb) py import gdb_util.stepping
(gdb) n
31          std::sort(data.begin(), data.end(),
(gdb) stepu

Breakpoint -27, operator() (__closure=0x7fffffffdf0f, a=std::vector of length 3, capacity 3 = {...}, 
    b=std::vector of length 3, capacity 3 = {...}) at ../../../game24/stl_with_lambda.cpp:33
33                        if (a[0] < b[0]) {
(gdb) l
28              {"Monoid", "Endofunctor", "Monad"}};
29 
30          // sample code targets the beginning of this call:
31          std::sort(data.begin(), data.end(),
32                    [](Strings const & a, Strings const & b) {
33                        if (a[0] < b[0]) {
34                            return true;
35                        } else {
36                            return a[1] < b[1];
37                        }

**Comment by jefftrull** [comment] 2021-05-15 19:41
Great! That's what it should look like.

I suspect that your system, like mine, uses 11.0 for llvm instead of 11.1, and this explains that issue.

I'm going to close this ticket unless you have other concerns. Thanks for the report.

**Comment by jiayuehua** [comment] 2021-05-17 12:09
Jeff, you can close the issue. Thank for your help.

**Comment by jefftrull** [comment] 2021-05-17 17:13
Reporter seems satisfied now

**Closed as completed by jefftrull** 2021-05-17 17:13 UTC
